version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./library_back/.env-sample

  django:
    container_name: django
    build:
      context: ./library_back
      dockerfile: Dockerfile
    restart: always
    env_file: ./library_back/.env-sample
    depends_on:
      - postgres
    links:
      - postgres

  nginx:
    container_name: nginx
    build:
      context: ./library_front
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - django
    links:
      - django

volumes:
  postgres_data:
    name: postgres_data
  react_build_data:
    name: react_build_data
