version: "3.9"

services:
  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: ./library_back/.env-sample

  api:
    container_name: api
    build:
      context: ./library_back/
      dockerfile: Dockerfile
    restart: always
    env_file: ./library_back/.env-sample
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db

  web:
    container_name: web
    build:
      context: ./library_front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    links:
      - api

volumes:
  pgdata:
    name: pgdata
