version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./library_back/.env-sample

  django:
    container_name: django
    build:
      context: ./library_back/
      dockerfile: Dockerfile
    restart: always
    env_file: ./library_back/.env-sample
    depends_on:
      - postgres
    links:
      - postgres

  react_build:
    container_name: react_build
    build:
      context: ./library_front
      dockerfile: Dockerfile
    volumes:
      - react_build_data:/app/build

  nginx:
    container_name: nginx
    image: nginx:1.23.1-alpine
    ports:
      - 80:8080
    volumes:
      - react_build_data:/var/www/web
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django
      - react_build
    links:
      - django

volumes:
  postgres_data:
    name: postgres_data
  react_build_data:
    name: react_build_data
